config/routes.rb
BootstrapApp::Application.routes.draw do
  

  devise_for :users, :controllers => {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users
  root :to => "home#index"

  resource :beers do
    get 'index'
  end

  resource :club do
    get 'signup'
  end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def signup
    if current_user.nil?
      redirect_to new_user_registration_url
    else
    end
  end
end

app/helpers/club_helper.rb
module ClubHelper
end

app/views/clubs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-6 well brand" style="font-size: 1.5em;line-height: 1.3em;">
      Thank you so much for signing up to be part of our pilot program! We are feverishly working to bring together a collection of the best craft brews around.  Please check back often for updates and we will be in touch when the new shipments are ready to be sent out.<br/><br/><div style="float: right;">Cheers!<br>The Barley Boxers</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
    </div>
    <div class="col-md-5 well brand" >
      <h4>In the interum...</h4>
      <p>Feel free to take a look at some of the quality beers that we're considering.</p>
      <button class="btn-success" style="float: right; font-size: 1.4em; letter-spacing: .08em;" onclick="location='<%= beers_path %>';">Show me beers!</button>
    </div>
  </div>
</div>

app/views/clubs/signup.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-6 well brand" style="font-size: 1.5em;line-height: 1.3em;">
      Thank you so much for signing up to be part of our pilot program! We are feverishly working to bring together a collection of the best craft brews around.  Please check back often for updates and we will be in touch when the new shipments are ready to be sent out.<br/><br/><div style="float: right;">Cheers!<br>The Barley Boxers</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
    </div>
    <div class="col-md-5 well brand" >
      <h4>In the interum...</h4>
      <p>Feel free to take a look at some of the quality beers that we're considering.</p>
      <button class="btn-success" style="float: right; font-size: 1.4em; letter-spacing: .08em;" onclick="location='<%= beers_path %>';">Show me beers!</button>
    </div>
  </div>
</div>