config/routes.rb
BootstrapApp::Application.routes.draw do
  

  devise_for :users, :controllers => {
    registrations: "users/registrations", 
    passwords: "users/passwords", 
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users
  root :to => "home#index"

  resource :beers do
    get 'index'
  end

  resource :club do
    get 'signup'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless current_user.nil?
      redirect_to club_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 well brand" style="font-size: 1.5em;line-height: 1.3em;">
      We are Craft Beer enthusiasts who have a desire to explore new beers. Barley Box is a home subscription service that delivers beer to people like us. Unlike existing services, Barley Box delivers a great story along side our quality product. We have no competition because we are a premium service at an affordable price.<br/><br/><div style="float: right;">BarleyBox - drink</div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-5 col-md-offset-7 well brand" >
      <h4>Interested in premium craft brews with a great story?</h4>
      <p>We're looking for individuals who are interested in participating in an exclusive pilot program.</p>
      <button class="btn-success" style="float: right; font-size: 1.4em; letter-spacing: .08em;" onclick="location='<%= signup_club_path %>';">Sign up now!</button>
    </div>
  </div>
</div>